sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
services:
  - mongodb
  - mysql
  - postgresql
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c "create database test;" -U postgres
before_script:
  - export VFS_MONGO_TEST_CONFIG='{"vfs":{"mongo":{"hostspec":"localhost"}}}';
    export VFS_SQL_MYSQL_TEST_CONFIG='{"vfs":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export VFS_SQL_MYSQLI_TEST_CONFIG='{"vfs":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export VFS_SQL_PDO_MYSQL_TEST_CONFIG='{"vfs":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export VFS_SQL_PDO_PGSQL_TEST_CONFIG='{"vfs":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ $(echo "$TRAVIS_PHP_VERSION 7.0" | tr " " "\n" | sort -V | head -n1) = "7.0" ];
    then
        phpenv config-add .travis.php7.ini;
    else
        phpenv config-add .travis.ini;
    fi
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(find test -name AllTests.php)
